//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEvaluacionEntities : DbContext
    {
        public DBEvaluacionEntities()
            : base("name=DBEvaluacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENCIA> AGENCIAs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<TIPO_VIVIENDA> TIPO_VIVIENDA { get; set; }
        public virtual DbSet<VENTA> VENTAs { get; set; }
        public virtual DbSet<VIVIENDA> VIVIENDAs { get; set; }
    }
}
