//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIVIENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIVIENDA()
        {
            this.VENTAs = new HashSet<VENTA>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NUMERO_CUARTOS { get; set; }
        public Nullable<int> NUMERO_BAÑOS { get; set; }
        public Nullable<double> TAMAÑO_MCUADRADO { get; set; }
        public Nullable<int> NUMERO_PISOS { get; set; }
        public string ACCESORIOS { get; set; }
        public Nullable<int> ID_TIPO_VIVIENDA { get; set; }
        public Nullable<decimal> VALOR_VIVIENDA { get; set; }
    
        public virtual TIPO_VIVIENDA TIPO_VIVIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTAs { get; set; }
    }
}
